name: CI Check

on:
  pull_request:
    branches:
      - dev

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Get Changed Files
        id: changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const files = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const fileNames = files.data.map(f => f.filename).join(' ');
            core.setOutput('files', fileNames);

      - name: Run Checkstyle
        run: mvn checkstyle:check -Dcheckstyle.includes="${{ steps.changed-files.outputs.files }}"
        if: steps.changed-files.outputs.files != ''
    
      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test