name: CI Check

on:
  pull_request:
    branches:
      - dev

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Fetch Branches
        run: git fetch origin

      - name: Get Modified Files
        id: get-files
        run: |
          base_commit=${{ github.event.pull_request.base.sha }}
          current_commit=${{ github.sha }}
          modified_files=$(git diff --name-only $base_commit $current_commit -- '*.java')
          echo "Modified files: $modified_files"
          echo "FILES=$modified_files" >> $GITHUB_ENV

      - name: Debug Files Variable
        run: echo "FILES: $FILES"

      - name: Run Checkstyle on Modified Files
        run: |
          if [ -n "$FILES" ]; then
            for file in $FILES; do
              # Verifica se o arquivo existe e se o caminho está correto
              if [ -f "$file" ]; then
                echo "Running Checkstyle on $file"
                mvn checkstyle:check -Dcheckstyle.includes="$file" || exit 1
              else
                echo "File $file does not exist."
              fi
            done
          else
            echo "No Java files were modified."
          fi

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test