name: CI Check

on:
  pull_request:
    branches:
      - dev

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Checkstyle on Modified Files
        run: |
          modified_files=$(git diff --name-only origin/dev...HEAD -- '*.java')
          if [ -n "$modified_files" ]; then
            for file in $modified_files; do
              mvn checkstyle:check -Dcheckstyle.includes=$file || exit 1
            done
          else
            echo "No Java files were modified."
          fi

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test